export type PlaywrightInterface = "Page" | "Locator";
export type ApiCompatibility = "Full" | "Partial" | "Unsupported";
export type ExecutionFidelity = "Matched" | "Browser-emulated";

type CompatibilityMemberBase = {
  interface: PlaywrightInterface;
  member: string;
};

export type FullCompatibilityMember = CompatibilityMemberBase & {
  api: "Full";
  execution: ExecutionFidelity;
  note?: string;
  reason?: never;
};

export type PartialCompatibilityMember = CompatibilityMemberBase & {
  api: "Partial";
  execution: ExecutionFidelity;
  note: string;
  reason?: never;
};

export type UnsupportedCompatibilityMember = CompatibilityMemberBase & {
  api: "Unsupported";
  reason: string;
  execution?: never;
  note?: never;
};

export type CompatibilityMember =
  | FullCompatibilityMember
  | PartialCompatibilityMember
  | UnsupportedCompatibilityMember;

const pageMembers = [
  "evaluate",
  "evaluateHandle",
  "addInitScript",
  "$",
  "$$",
  "$eval",
  "$$eval",
  "waitForFunction",
  "waitForSelector",
  "exposeBinding",
  "removeAllListeners",
  "on",
  "once",
  "addListener",
  "removeListener",
  "off",
  "prependListener",
  "addLocatorHandler",
  "addScriptTag",
  "addStyleTag",
  "ariaSnapshot",
  "bringToFront",
  "cancelPickLocator",
  "check",
  "clearConsoleMessages",
  "clearPageErrors",
  "click",
  "close",
  "consoleMessages",
  "content",
  "context",
  "dblclick",
  "dispatchEvent",
  "dragAndDrop",
  "emulateMedia",
  "exposeFunction",
  "fill",
  "focus",
  "frame",
  "frameLocator",
  "frames",
  "getAttribute",
  "getByAltText",
  "getByLabel",
  "getByPlaceholder",
  "getByRole",
  "getByTestId",
  "getByText",
  "getByTitle",
  "goBack",
  "goForward",
  "goto",
  "hideHighlight",
  "hover",
  "innerHTML",
  "innerText",
  "inputValue",
  "isChecked",
  "isClosed",
  "isDisabled",
  "isEditable",
  "isEnabled",
  "isHidden",
  "isVisible",
  "locator",
  "mainFrame",
  "opener",
  "pageErrors",
  "pause",
  "pdf",
  "pickLocator",
  "press",
  "reload",
  "removeLocatorHandler",
  "requestGC",
  "requests",
  "route",
  "routeFromHAR",
  "routeWebSocket",
  "screenshot",
  "selectOption",
  "setChecked",
  "setContent",
  "setDefaultNavigationTimeout",
  "setDefaultTimeout",
  "setExtraHTTPHeaders",
  "setInputFiles",
  "setViewportSize",
  "tap",
  "textContent",
  "title",
  "type",
  "uncheck",
  "unroute",
  "unrouteAll",
  "url",
  "video",
  "viewportSize",
  "waitForEvent",
  "waitForLoadState",
  "waitForNavigation",
  "waitForRequest",
  "waitForResponse",
  "waitForTimeout",
  "waitForURL",
  "workers",
  "clock",
  "coverage",
  "keyboard",
  "localStorage",
  "mouse",
  "request",
  "screencast",
  "sessionStorage",
  "touchscreen",
  "[Symbol.asyncDispose]",
] as const;

const locatorMembers = [
  "evaluate",
  "evaluateHandle",
  "evaluateAll",
  "waitForFunction",
  "elementHandle",
  "highlight",
  "toString",
  "all",
  "allInnerTexts",
  "allTextContents",
  "and",
  "ariaSnapshot",
  "blur",
  "boundingBox",
  "check",
  "clear",
  "click",
  "contentFrame",
  "count",
  "dblclick",
  "describe",
  "description",
  "dispatchEvent",
  "dragTo",
  "drop",
  "elementHandles",
  "fill",
  "filter",
  "first",
  "focus",
  "frameLocator",
  "getAttribute",
  "getByAltText",
  "getByLabel",
  "getByPlaceholder",
  "getByRole",
  "getByTestId",
  "getByText",
  "getByTitle",
  "hideHighlight",
  "hover",
  "innerHTML",
  "innerText",
  "inputValue",
  "isChecked",
  "isDisabled",
  "isEditable",
  "isEnabled",
  "isHidden",
  "isVisible",
  "last",
  "locator",
  "normalize",
  "nth",
  "or",
  "page",
  "press",
  "pressSequentially",
  "screenshot",
  "scrollIntoViewIfNeeded",
  "selectOption",
  "selectText",
  "setChecked",
  "setInputFiles",
  "tap",
  "textContent",
  "type",
  "uncheck",
  "waitFor",
] as const;

const fullMatched = new Set([
  "Page.$$eval",
  "Page.$eval",
  "Page.ariaSnapshot",
  "Page.content",
  "Page.evaluate",
  "Page.getAttribute",
  "Page.getByAltText",
  "Page.getByLabel",
  "Page.getByPlaceholder",
  "Page.getByRole",
  "Page.getByTestId",
  "Page.getByText",
  "Page.getByTitle",
  "Page.hideHighlight",
  "Page.innerHTML",
  "Page.innerText",
  "Page.inputValue",
  "Page.isChecked",
  "Page.isDisabled",
  "Page.isEditable",
  "Page.isEnabled",
  "Page.isHidden",
  "Page.isVisible",
  "Page.localStorage",
  "Page.locator",
  "Page.sessionStorage",
  "Page.setDefaultTimeout",
  "Page.textContent",
  "Page.title",
  "Page.url",
  "Page.viewportSize",
  "Page.waitForTimeout",
  "Locator.all",
  "Locator.allInnerTexts",
  "Locator.allTextContents",
  "Locator.and",
  "Locator.ariaSnapshot",
  "Locator.boundingBox",
  "Locator.count",
  "Locator.describe",
  "Locator.description",
  "Locator.evaluate",
  "Locator.evaluateAll",
  "Locator.filter",
  "Locator.first",
  "Locator.getAttribute",
  "Locator.getByAltText",
  "Locator.getByLabel",
  "Locator.getByPlaceholder",
  "Locator.getByRole",
  "Locator.getByTestId",
  "Locator.getByText",
  "Locator.getByTitle",
  "Locator.hideHighlight",
  "Locator.highlight",
  "Locator.innerHTML",
  "Locator.innerText",
  "Locator.inputValue",
  "Locator.isChecked",
  "Locator.isDisabled",
  "Locator.isEditable",
  "Locator.isEnabled",
  "Locator.isHidden",
  "Locator.isVisible",
  "Locator.last",
  "Locator.locator",
  "Locator.normalize",
  "Locator.nth",
  "Locator.or",
  "Locator.page",
  "Locator.textContent",
  "Locator.toString",
  "Locator.waitFor",
  "Locator.waitForFunction",
]);

const fullBrowserEmulated = new Set([
  "Page.addLocatorHandler",
  "Page.cancelPickLocator",
  "Page.check",
  "Page.clearPageErrors",
  "Page.click",
  "Page.clock",
  "Page.dblclick",
  "Page.dispatchEvent",
  "Page.dragAndDrop",
  "Page.exposeBinding",
  "Page.exposeFunction",
  "Page.fill",
  "Page.focus",
  "Page.hover",
  "Page.keyboard",
  "Page.mouse",
  "Page.pageErrors",
  "Page.pickLocator",
  "Page.press",
  "Page.removeLocatorHandler",
  "Page.setChecked",
  "Page.setContent",
  "Page.tap",
  "Page.touchscreen",
  "Page.type",
  "Page.uncheck",
  "Locator.blur",
  "Locator.check",
  "Locator.clear",
  "Locator.click",
  "Locator.dblclick",
  "Locator.dispatchEvent",
  "Locator.dragTo",
  "Locator.fill",
  "Locator.focus",
  "Locator.hover",
  "Locator.press",
  "Locator.pressSequentially",
  "Locator.scrollIntoViewIfNeeded",
  "Locator.selectText",
  "Locator.setChecked",
  "Locator.tap",
  "Locator.type",
  "Locator.uncheck",
]);

const partialBrowserEmulated = new Map<string, string>([
  [
    "Page.selectOption",
    "String and SelectOption inputs are supported; Playwright ElementHandle input branches are not.",
  ],
  [
    "Page.setInputFiles",
    "In-memory FilePayload inputs are supported; filesystem path inputs are unavailable in an in-page browser runtime.",
  ],
  [
    "Locator.drop",
    "Data items and in-memory file payloads are supported; filesystem path inputs are not.",
  ],
  [
    "Locator.selectOption",
    "String and SelectOption inputs are supported; Playwright ElementHandle input branches are not.",
  ],
  [
    "Locator.setInputFiles",
    "In-memory FilePayload inputs are supported; filesystem path inputs are unavailable in an in-page browser runtime.",
  ],
]);

const unsupportedReasons: Record<PlaywrightInterface, string> = {
  Page: "Requires Playwright-owned objects, browser-level control, or a lifetime outside the page runtime.",
  Locator:
    "Requires Playwright-owned frame or handle objects, or browser-level screenshot control.",
};

function classify(
  interfaceName: PlaywrightInterface,
  member: string
): CompatibilityMember {
  const key = `${interfaceName}.${member}`;
  if (fullBrowserEmulated.has(key))
    return {
      interface: interfaceName,
      member,
      api: "Full",
      execution: "Browser-emulated",
    };
  if (fullMatched.has(key))
    return {
      interface: interfaceName,
      member,
      api: "Full",
      execution: "Matched",
    };
  const note = partialBrowserEmulated.get(key);
  if (note)
    return {
      interface: interfaceName,
      member,
      api: "Partial",
      execution: "Browser-emulated",
      note,
    };
  return {
    interface: interfaceName,
    member,
    api: "Unsupported",
    reason: unsupportedReasons[interfaceName],
  };
}

/** The exhaustive pinned public surface, independent from the selected support. */
export const compatibilityCatalog: readonly CompatibilityMember[] = [
  ...pageMembers.map((member) => classify("Page", member)),
  ...locatorMembers.map((member) => classify("Locator", member)),
];
