export type PlaywrightInterface = "Page" | "Locator";
export type ApiCompatibility = "Full" | "Partial" | "Unsupported";
export type ExecutionFidelity = "Matched" | "Browser-emulated";

export type CompatibilityMember = {
  interface: PlaywrightInterface;
  member: string;
  api: ApiCompatibility;
  execution: ExecutionFidelity;
};

const pageMembers = [
  "evaluate",
  "evaluateHandle",
  "addInitScript",
  "$",
  "$$",
  "$eval",
  "$$eval",
  "waitForFunction",
  "waitForSelector",
  "exposeBinding",
  "removeAllListeners",
  "on",
  "once",
  "addListener",
  "removeListener",
  "off",
  "prependListener",
  "addLocatorHandler",
  "addScriptTag",
  "addStyleTag",
  "ariaSnapshot",
  "bringToFront",
  "cancelPickLocator",
  "check",
  "clearConsoleMessages",
  "clearPageErrors",
  "click",
  "close",
  "consoleMessages",
  "content",
  "context",
  "dblclick",
  "dispatchEvent",
  "dragAndDrop",
  "emulateMedia",
  "exposeFunction",
  "fill",
  "focus",
  "frame",
  "frameLocator",
  "frames",
  "getAttribute",
  "getByAltText",
  "getByLabel",
  "getByPlaceholder",
  "getByRole",
  "getByTestId",
  "getByText",
  "getByTitle",
  "goBack",
  "goForward",
  "goto",
  "hideHighlight",
  "hover",
  "innerHTML",
  "innerText",
  "inputValue",
  "isChecked",
  "isClosed",
  "isDisabled",
  "isEditable",
  "isEnabled",
  "isHidden",
  "isVisible",
  "locator",
  "mainFrame",
  "opener",
  "pageErrors",
  "pause",
  "pdf",
  "pickLocator",
  "press",
  "reload",
  "removeLocatorHandler",
  "requestGC",
  "requests",
  "route",
  "routeFromHAR",
  "routeWebSocket",
  "screenshot",
  "selectOption",
  "setChecked",
  "setContent",
  "setDefaultNavigationTimeout",
  "setDefaultTimeout",
  "setExtraHTTPHeaders",
  "setInputFiles",
  "setViewportSize",
  "tap",
  "textContent",
  "title",
  "type",
  "uncheck",
  "unroute",
  "unrouteAll",
  "url",
  "video",
  "viewportSize",
  "waitForEvent",
  "waitForLoadState",
  "waitForNavigation",
  "waitForRequest",
  "waitForResponse",
  "waitForTimeout",
  "waitForURL",
  "workers",
  "clock",
  "coverage",
  "keyboard",
  "localStorage",
  "mouse",
  "request",
  "screencast",
  "sessionStorage",
  "touchscreen",
  "[Symbol.asyncDispose]",
] as const;

const locatorMembers = [
  "evaluate",
  "evaluateHandle",
  "evaluateAll",
  "waitForFunction",
  "elementHandle",
  "highlight",
  "toString",
  "all",
  "allInnerTexts",
  "allTextContents",
  "and",
  "ariaSnapshot",
  "blur",
  "boundingBox",
  "check",
  "clear",
  "click",
  "contentFrame",
  "count",
  "dblclick",
  "describe",
  "description",
  "dispatchEvent",
  "dragTo",
  "drop",
  "elementHandles",
  "fill",
  "filter",
  "first",
  "focus",
  "frameLocator",
  "getAttribute",
  "getByAltText",
  "getByLabel",
  "getByPlaceholder",
  "getByRole",
  "getByTestId",
  "getByText",
  "getByTitle",
  "hideHighlight",
  "hover",
  "innerHTML",
  "innerText",
  "inputValue",
  "isChecked",
  "isDisabled",
  "isEditable",
  "isEnabled",
  "isHidden",
  "isVisible",
  "last",
  "locator",
  "normalize",
  "nth",
  "or",
  "page",
  "press",
  "pressSequentially",
  "screenshot",
  "scrollIntoViewIfNeeded",
  "selectOption",
  "selectText",
  "setChecked",
  "setInputFiles",
  "tap",
  "textContent",
  "type",
  "uncheck",
  "waitFor",
] as const;

const fullMatched = new Set([
  "Page.content",
  "Page.getByAltText",
  "Page.getByLabel",
  "Page.getByPlaceholder",
  "Page.getByRole",
  "Page.getByTestId",
  "Page.getByText",
  "Page.getByTitle",
  "Page.locator",
  "Page.title",
  "Page.url",
  "Locator.all",
  "Locator.allInnerTexts",
  "Locator.allTextContents",
  "Locator.and",
  "Locator.ariaSnapshot",
  "Locator.count",
  "Locator.filter",
  "Locator.first",
  "Locator.getAttribute",
  "Locator.getByAltText",
  "Locator.getByLabel",
  "Locator.getByPlaceholder",
  "Locator.getByRole",
  "Locator.getByTestId",
  "Locator.getByText",
  "Locator.getByTitle",
  "Locator.innerHTML",
  "Locator.innerText",
  "Locator.inputValue",
  "Locator.isChecked",
  "Locator.isDisabled",
  "Locator.isEditable",
  "Locator.isEnabled",
  "Locator.isHidden",
  "Locator.isVisible",
  "Locator.last",
  "Locator.locator",
  "Locator.nth",
  "Locator.or",
  "Locator.page",
  "Locator.textContent",
  "Locator.waitFor",
]);

const fullBrowserEmulated = new Set([
  "Locator.click",
  "Locator.fill",
  "Locator.focus",
  "Locator.press",
]);

function classify(
  interfaceName: PlaywrightInterface,
  member: string
): CompatibilityMember {
  const key = `${interfaceName}.${member}`;
  if (fullBrowserEmulated.has(key))
    return {
      interface: interfaceName,
      member,
      api: "Full",
      execution: "Browser-emulated",
    };
  if (fullMatched.has(key))
    return {
      interface: interfaceName,
      member,
      api: "Full",
      execution: "Matched",
    };
  return {
    interface: interfaceName,
    member,
    api: "Unsupported",
    execution: "Matched",
  };
}

/** The exhaustive pinned public surface, independent from the selected support. */
export const compatibilityCatalog: readonly CompatibilityMember[] = [
  ...pageMembers.map((member) => classify("Page", member)),
  ...locatorMembers.map((member) => classify("Locator", member)),
];
